
export const ORDER_DATA_REQUEST = 'ORDER_DATA';
export const ORDER_DATA_SUCCESS = 'ORDER_DATA_SUCCESS';
export const ORDER_DATA_FAILED = 'ORDER_DATA_FAILED';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const ORDER_NUMBER_REQUEST = 'ORDER_NUMBER_REQUEST';
export const ORDER_NUMBER_DELETE = 'ORDER_NUMBER_DELETE';

export const ADD_COMPONENT = 'ADD_COMPONENT';
export const DELETE_COMPONENT = 'DELETE_COMPONENT';
export const UPDATE_CONSTRUCTOR_LIST = 'UPDATE_CONSTRUCTOR_LIST'

export const DELETE_BUN = 'DELETE_BUN';