
export const ORDER_DATA_REQUEST = 'ORDER_DATA';
export const ORDER_DATA_SUCCESS = 'ORDER_DATA_SUCCESS';
export const ORDER_DATA_FAILED = 'ORDER_DATA_FAILED';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const ORDER_NUMBER_REQUEST = 'ORDER_NUMBER_REQUEST';
export const ORDER_NUMBER_SUCCESS = 'ORDER_POST_SUCCESS';
export const ORDER_NUMBER_FAILED = 'ORDER_POST_FAILED';
